#ifndef MRIUTILS_H
#define MRIUTILS_H

# include <stdio.h>
# include <stdlib.h>
# include <math.h>
# include <limits.h>
# include <iostream>
# include <fstream>
# include <sstream>
# include <vector>
# include <boost/algorithm/string.hpp>
# include "mpi.h"

# include "mriConstants.h"
# include "mriException.h"
# include "mriThresholdCriteria.h"
# include "mriTypes.h"

using namespace std;

// PRINT FUNCTIONS 
// WRITE PROGRAM HEADER
void writeHeader();
// WRITE MESSAGE TO SCREEN
void writeSchMessage(std::string Msg);

// MRI UTILITIES
namespace MRIUtils{

  // GLOBAL VARIABLE FOR BOOST RANDOM NUMBER GENERATION
  static boost::random::mt19937 realGen;

  // Write Help
  void writeProgramHelp();

  // Home made Int to String Conversion
  string intToStr(int number);

  // Home made Float to String Conversion
  string floatToStr(double number);

  // Own String Split Method
  MRIStringVec extractSubStringFromBufferMS(string Buffer);

  double do3DEucNorm(const MRIDoubleVec& v);

  void normalize3DVector(MRIDoubleVec& v);

  // Insert Value in String 
  template<typename Type> void insertInList(Type value, vector<Type>& coords);

  // Sample from Standard Gaussian Distribution
  double generateStandardGaussian(double stDev);

  // Round Floating Point Value
  int round(double value);

  // Write Abcissae and Ordinates to file
  void writeGraphToFile(string fileName, int vecSize, MRIDoubleVec& vecX, MRIDoubleVec& vecY);

  // Perform 3D External Product
  void do3DExternalProduct(const MRIDoubleVec& v1, const MRIDoubleVec& v2, MRIDoubleVec& resVec);

  // Check if Point is Inside/Outside Box
  bool isPointInsideBox(double xCoord, double yCoord, double zCoord, const MRIDoubleVec& limitBox);

  // Print Binary Array To File
  void printBinArrayToFile(string fileName, int numberOfBins, const MRIDoubleVec& binCenter, const MRIDoubleVec& binValues);

  // Apply Limit Box Factor
  void applyLimitBoxFactors(double xFactor, double yFactor, double zFactor, MRIDoubleVec& limitBox);

  // Print Matrix To File
  void printMatrixToFile(string fileName, const MRIDoubleMat& Mat);

  // Read List of Files
  void readFileList(string listName, MRIStringVec& fileList);

  // Read Matrix From File
  void readMatrixFromFile(string inFileName, int& nrow, int& ncol, MRIDoubleMat& inMat);

  // Get Median of Double Vector
  double getMedian(const MRIDoubleVec& v);

  // Get Mean of Double Vector
  double getMean(const MRIDoubleVec& v);

  // Get Eigenvalues of 3x3 Matrix
  void compute3x3MatrixEigenvals(double A[3][3], double root[3]);

  // Bouble Sort Array of Integer
  void sortIntArray(MRIIntVec& faceIds);

  // Check that two integer vectors are the same
  bool isSameIntVector(const MRIIntVec& first, const MRIIntVec& second);

  // FIND HOW MANY INTERVALS
  int findHowMany(double distance, std::vector<double> lengths);

  // CHECK ERROR GENERATED BY MPI
  void checkMpiError(int mpiError);

  // GET THRESHOLD QUANTITY STRING
  string getThresholdQtyString(int thresholdQty);

  // GET THRESHOLD TYPE STRING
  string getThresholdTypeString(int thresholdType);

  // GET MIN OF STD INT VECTOR
  int getMinInt(vector<int> vec);

  // CHECK IF STRING IS A FLOATING POINT
  bool isFloat(string token);

  // READ TABLE FROM FILE
  int readTableFromFile(string fileName, MRIDoubleMat& table,bool skipFirstRow);

  // PRINT DOUBLE MATRIX
  void printDoubleMatToFile(string fileName, const MRIDoubleMat& faceNormals);

  // PRINT INT MATRIX
  void printIntMatToFile(string fileName, const MRIIntMat& mat);

  // PRINT DOUBLE VECTOR
  void printDoubleVecToFile(string fileName, const MRIDoubleVec& vec);

  // PRINT DOUBLE VECTOR
  void printIntVecToFile(string fileName, const MRIIntVec& vec);

  // PRINT DOUBLE MATRIX
  void printDoubleArrayToFile(string fileName, int size, double* vec);

  // NORMALIZE BIN ARRAY
  void normalizeBinArray(MRIDoubleVec& binArray,double currInterval);

  // ASSIGN TO BIN ARRAY
  void assignToBin(double currValue, int numberOfBins, const MRIDoubleVec& binMin, const MRIDoubleVec& binMax, MRIDoubleVec& binArray);

}
#endif //MRIUTILS_H
